(()=>{
'use strict';
const $=id=>document.getElementById(id);
const p=new URLSearchParams(location.search);
const projectId=p.get('project')||'';
const projectTitle=p.get('title')||'Proyecto educativo';
const course=p.get('course')||'';
const level=p.get('level')||'Universitario';
const API=location.hostname.endsWith('onrender.com')?'https://ucan-reality-lab.onrender.com/api':'/api';
const token=()=>localStorage.getItem('ucan_access_token')||'';
let imageData='';let modelTerms=[];let saveTimer;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const authHeaders=(extra={})=>({...extra,Authorization:`Bearer ${token()}`});
async function json(r){const b=await r.json().catch(()=>({}));if(!r.ok)throw Error(b.detail||`Error ${r.status}`);return b}
function setValue(id,v){const el=$(id);if(el)el.value=v??''}
function rubricRows(){return [...document.querySelectorAll('.rubric-row')].map(r=>({name:r.querySelector('.rn').value,points:Number(r.querySelector('.rp').value)||0,levels:r.querySelector('.rl').value}))}
function addRubricRow(c={name:'Criterio',points:25,levels:'Excelente, competente, en desarrollo e insuficiente'}){const d=document.createElement('div');d.className='rubric-row';d.innerHTML='<input class="rn" aria-label="Criterio"><input class="rp" aria-label="Puntos" type="number" min="0" max="100"><input class="rl" aria-label="Niveles"><button type="button" class="secondary">Eliminar</button>';d.querySelector('.rn').value=c.name;d.querySelector('.rp').value=c.points;d.querySelector('.rl').value=c.levels;d.querySelector('button').onclick=()=>{d.remove();changed()};d.querySelectorAll('input').forEach(x=>x.addEventListener('input',changed));$('rubric').appendChild(d)}
function rubricTotal(){const n=rubricRows().reduce((s,r)=>s+r.points,0);$('rubricTotal').textContent=`Total: ${n}/100 ${n===100?'✓':'— ajuste los puntos'}`;$('rubricTotal').className=n===100?'success':'error';return n}
function topic(){return $('resourceDescription').value.trim()||projectTitle}
function renderModelSources(){const terms=modelTerms.length?modelTerms:[topic(),`${topic()} 3D model`,`${topic()} GLB`];const q=encodeURIComponent(terms[0].slice(0,120));$('modelTerms').innerHTML=`<b>Términos sugeridos:</b> ${terms.map(t=>`<span class="chip">${esc(t)}</span>`).join('')}`;const bio=/biolog|anatom|célul|salud|medic/i.test(terms.join(' '));const sources=[['Sketchfab','Modelos interactivos y científicos',`https://sketchfab.com/search?type=models&q=${q}`],['Smithsonian 3D','Patrimonio, ciencia e historia',`https://3d.si.edu/explore?search=${q}`],[bio?'NIH 3D':'NASA 3D',bio?'Biomedicina y anatomía':'Ciencia, espacio y tecnología',bio?`https://3d.nih.gov/discover?search=${q}`:`https://nasa3d.arc.nasa.gov/search?search=${q}`]];$('modelSources').innerHTML=sources.map(s=>`<article class="model-card"><h3>${s[0]}</h3><p>${s[1]}</p><a class="btn secondary" target="_blank" rel="noopener" href="${s[2]}">Buscar modelo</a></article>`).join('')}
function localDesign(){const t=topic();const advanced=/maestr|doctor/i.test(level);setValue('activityTitle',`${advanced?'Evaluación crítica':'Análisis aplicado'}: ${t.slice(0,95)}`);setValue('bloom',advanced?'Evaluar':'Analizar');setValue('objectives',`1. Identificar los conceptos y componentes principales relacionados con ${t}.\n2. Explicar sus relaciones, funciones o implicaciones.\n3. Aplicar los conceptos de ${course||'la materia'} mediante evidencia del recurso.\n4. Comunicar conclusiones claras, organizadas y fundamentadas.`);setValue('instructions',`Examine cuidadosamente el recurso educativo. Identifique sus elementos principales, documente evidencia relevante y relacione sus observaciones con los conceptos de ${course||'este curso'}. Responda la pregunta central y revise la rúbrica antes de entregar.`);setValue('question','¿Cuáles son los elementos centrales del recurso, cómo se relacionan y qué evidencia sustenta su análisis?');setValue('expected','La respuesta debe identificar elementos verificables, explicar relaciones o funciones, aplicar conceptos del curso, utilizar evidencia y presentar una conclusión fundamentada.');setValue('quiz1','Identifique tres elementos principales y explique la importancia de cada uno.');setValue('quiz2','¿Qué relación existe entre los componentes o conceptos observados?');setValue('quiz3','¿Cómo aplicaría este aprendizaje a una situación auténtica?');setValue('resourceAlt',`Recurso educativo relacionado con ${t}.`);if(!$('modelAlt').value)setValue('modelAlt',`Modelo tridimensional relacionado con ${t}.`);modelTerms=[t,`${t} 3D model`,`${t} GLB`];renderModelSources();$('rubric').innerHTML='';[['Dominio del contenido',25],['Análisis y evidencia',30],['Aplicación y pensamiento crítico',25],['Organización y comunicación',20]].forEach(x=>addRubricRow({name:x[0],points:x[1],levels:'Excelente, competente, en desarrollo e insuficiente'}));rubricTotal();$('designStatus').className='status success';$('designStatus').textContent='Actividad creada automáticamente. Puede editarla antes de publicar.';refreshPreview();scheduleSave()}
async function improveWithAI(){if(!imageData||!token())return;try{$('designStatus').textContent='Analizando la imagen con IA…';const r=await fetch(`${API}/ai/design-from-image`,{method:'POST',headers:authHeaders({'Content-Type':'application/json'}),body:JSON.stringify({image_url:imageData,project_title:projectTitle,course,academic_level:level,teacher_goal:$('resourceDescription').value,language:'es-PR'})});const b=await json(r);setValue('activityTitle',b.activity_title);setValue('bloom',b.bloom_level);setValue('objectives',b.objectives);setValue('instructions',b.instructions);setValue('question',b.main_question);setValue('expected',b.expected_answer);(b.quiz||[]).slice(0,3).forEach((q,i)=>setValue(`quiz${i+1}`,q));setValue('resourceAlt',b.image_summary||b.model_accessibility_description);setValue('modelAlt',b.model_accessibility_description);modelTerms=b.model_search_terms||modelTerms;renderModelSources();if(Array.isArray(b.rubric)&&b.rubric.length){$('rubric').innerHTML='';b.rubric.forEach(addRubricRow)}rubricTotal();$('designStatus').className='status success';$('designStatus').textContent='La IA analizó la imagen y mejoró la actividad.';refreshPreview();scheduleSave()}catch(e){$('designStatus').className='status error';$('designStatus').textContent=`La actividad local fue creada, pero la mejora con IA no se completó: ${e.message}`}}
function sketchfabId(v){const m=v.match(/sketchfab\.com\/(?:3d-models\/[^/?#]+-|models\/)([a-f0-9]{32})/i);return m?.[1]||''}
function modelMarkup(v=$('modelUrl').value,alt=$('modelAlt').value){v=String(v||'').trim();if(!v)return'';const iframe=v.match(/<iframe[^>]+src=["']([^"']+)["']/i);if(iframe)return`<iframe title="Modelo 3D" allow="autoplay; fullscreen; xr-spatial-tracking" allowfullscreen src="${esc(iframe[1])}"></iframe>`;const id=sketchfabId(v);if(id)return`<iframe title="Modelo 3D" allow="autoplay; fullscreen; xr-spatial-tracking" allowfullscreen src="https://sketchfab.com/models/${id}/embed"></iframe>`;if(/^https:\/\/.*\.(glb|gltf)(\?|#|$)/i.test(v))return`<model-viewer src="${esc(v)}" alt="${esc(alt||'Modelo 3D educativo')}" camera-controls auto-rotate shadow-intensity="1"></model-viewer>`;return''}
function showModel(){const html=modelMarkup();if(!html){$('modelStatus').className='status error';$('modelStatus').textContent='Use un enlace válido de Sketchfab, iframe o URL directa .glb/.gltf.';$('modelPreview').innerHTML='<span class="muted">No se pudo presentar el modelo.</span>';return}$('modelPreview').innerHTML=html;$('modelStatus').className='status success';$('modelStatus').textContent='Modelo 3D presentado correctamente.';refreshPreview();scheduleSave()}
function showResource(){if(imageData)$('resourcePreview').innerHTML=`<img src="${imageData}" alt="${esc($('resourceAlt').value||'Recurso educativo')}">`;else if(/^https:\/\//.test($('resourceUrl').value))$('resourcePreview').innerHTML=`<p><a target="_blank" rel="noopener" href="${esc($('resourceUrl').value)}">Abrir recurso</a></p>`;else $('resourcePreview').innerHTML='<span class="muted">Recurso sin vista previa.</span>'}
function state(){return{resourceType:$('resourceType').value,resourceUrl:$('resourceUrl').value,resourceDescription:$('resourceDescription').value,imageData,activityTitle:$('activityTitle').value,bloom:$('bloom').value,objectives:$('objectives').value,instructions:$('instructions').value,question:$('question').value,expected:$('expected').value,quiz:[$('quiz1').value,$('quiz2').value,$('quiz3').value],resourceAlt:$('resourceAlt').value,modelUrl:$('modelUrl').value,modelAlt:$('modelAlt').value,modelTerms,rubric:rubricRows()}}
function apply(d){if(!d)return;['resourceType','resourceUrl','resourceDescription','activityTitle','bloom','objectives','instructions','question','expected','resourceAlt','modelUrl','modelAlt'].forEach(id=>{if(d[id]!=null)setValue(id,d[id])});(d.quiz||[]).forEach((q,i)=>setValue(`quiz${i+1}`,q));imageData=d.imageData||'';modelTerms=d.modelTerms||[];$('rubric').innerHTML='';(d.rubric||[]).forEach(addRubricRow);if(!(d.rubric||[]).length)[['Dominio del contenido',25],['Análisis y evidencia',30],['Aplicación',25],['Comunicación',20]].forEach(x=>addRubricRow({name:x[0],points:x[1],levels:'Excelente, competente, en desarrollo e insuficiente'}));rubricTotal();showResource();renderModelSources();if($('modelUrl').value)showModel();refreshPreview()}
function refreshPreview(){const model=modelMarkup();$('studentPreview').innerHTML=`<h2>${esc($('activityTitle').value||projectTitle)}</h2>${imageData?`<img src="${imageData}" alt="${esc($('resourceAlt').value)}">`:''}${model}<h3>Objetivos</h3><p>${esc($('objectives').value).replace(/\n/g,'<br>')}</p><h3>Instrucciones</h3><p>${esc($('instructions').value).replace(/\n/g,'<br>')}</p><h3>Pregunta</h3><p>${esc($('question').value)}</p><textarea style="width:100%;min-height:130px" placeholder="Respuesta del estudiante"></textarea>`}
async function loadProjectInfo(){if(!projectId||!token())return;try{const pr=await json(await fetch(`${API}/projects/${projectId}`,{headers:authHeaders()}));$('projectName').textContent=pr.title;$('projectMeta').textContent=`${pr.course||'Curso no especificado'} · ${pr.academic_level}`;$('projectOwner').textContent=`Creado por: ${pr.owner_name||'Usuario institucional'}${pr.owner_email?' · '+pr.owner_email:''}`}catch{$('projectOwner').textContent='Información del creador no disponible.'}}
async function loadCloud(){if(!projectId||!token()){$('cloudState').textContent='Modo local';return}try{const r=await fetch(`${API}/projects/${projectId}/workspace`,{headers:authHeaders()});if(r.status===401){location.href='/';return}const b=await json(r);if(b.content&&Object.keys(b.content).length){apply(b.content);$('cloudState').textContent='Cargado de la nube'}else $('cloudState').textContent='Proyecto nuevo'}catch{$('cloudState').textContent='Modo local'}}
async function saveCloud(){localStorage.setItem(`ucan_v8_${projectId}`,JSON.stringify(state()));if(!projectId||!token()){$('cloudState').textContent='Guardado local';return}$('cloudState').textContent='Guardando…';try{await json(await fetch(`${API}/projects/${projectId}/workspace`,{method:'PUT',headers:authHeaders({'Content-Type':'application/json'}),body:JSON.stringify({content:state(),quality_score:80})}));$('cloudState').textContent='Guardado en la nube'}catch{$('cloudState').textContent='Guardado local; nube no disponible'}}
function scheduleSave(){clearTimeout(saveTimer);saveTimer=setTimeout(saveCloud,700)}function changed(){rubricTotal();refreshPreview();scheduleSave()}
function learner(d,scorm='web'){const api=scorm==='12'?`let a=window.API||parent.API;if(a){a.LMSInitialize('');a.LMSSetValue('cmi.core.lesson_status','incomplete')}function send(){if(a){a.LMSSetValue('cmi.core.lesson_status','completed');a.LMSSetValue('cmi.suspend_data',answer.value.slice(0,4000));a.LMSCommit('')}alert('Respuesta enviada')}`:scorm==='2004'?`let a=window.API_1484_11||parent.API_1484_11;if(a){a.Initialize('');a.SetValue('cmi.completion_status','incomplete')}function send(){if(a){a.SetValue('cmi.completion_status','completed');a.SetValue('cmi.suspend_data',answer.value.slice(0,4000));a.Commit('')}alert('Respuesta enviada')}`:`function send(){localStorage.setItem('ucanAnswer',answer.value);alert('Respuesta guardada')}`;return`<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>${esc(d.activityTitle)}</title><script type="module" src="https://unpkg.com/@google/model-viewer/dist/model-viewer.min.js"></script><style>body{font-family:Arial;max-width:950px;margin:auto;padding:24px;line-height:1.5}img,iframe,model-viewer{width:100%;max-height:520px;min-height:360px;border:0}textarea{width:100%;min-height:180px}table{width:100%;border-collapse:collapse}td,th{border:1px solid #bbb;padding:8px}button{padding:10px 16px;background:#08775d;color:white;border:0;border-radius:8px}</style></head><body><h1>${esc(d.activityTitle)}</h1>${d.imageData?`<img src="${d.imageData}" alt="${esc(d.resourceAlt)}">`:''}${modelMarkup(d.modelUrl,d.modelAlt)}<h2>Objetivos</h2><p>${esc(d.objectives).replace(/\n/g,'<br>')}</p><h2>Instrucciones</h2><p>${esc(d.instructions).replace(/\n/g,'<br>')}</p><h2>Pregunta</h2><p>${esc(d.question)}</p><textarea id="answer"></textarea><button onclick="send()">Enviar</button><h2>Rúbrica</h2><table><tr><th>Criterio</th><th>Puntos</th><th>Niveles</th></tr>${d.rubric.map(r=>`<tr><td>${esc(r.name)}</td><td>${r.points}</td><td>${esc(r.levels)}</td></tr>`).join('')}</table><script>${api}</script></body></html>`}
function download(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
async function packageScorm(ver){if(rubricTotal()!==100||!$('activityTitle').value||!$('instructions').value||!$('question').value){$('publishStatus').className='error';$('publishStatus').textContent='Complete la actividad y asegure que la rúbrica sume 100 puntos.';return}const d=state(),z=new JSZip(),title=esc(d.activityTitle);const manifest=ver==='12'?`<?xml version="1.0"?><manifest identifier="UCAN-${projectId}" xmlns="http://www.imsproject.org/xsd/imscp_rootv1p1p2" xmlns:adlcp="http://www.adlnet.org/xsd/adlcp_rootv1p2"><organizations default="ORG"><organization identifier="ORG"><title>${title}</title><item identifier="ITEM" identifierref="RES"><title>${title}</title></item></organization></organizations><resources><resource identifier="RES" type="webcontent" adlcp:scormtype="sco" href="index.html"><file href="index.html"/></resource></resources></manifest>`:`<?xml version="1.0"?><manifest identifier="UCAN-${projectId}" xmlns="http://www.imsglobal.org/xsd/imscp_v1p1" xmlns:adlcp="http://www.adlnet.org/xsd/adlcp_v1p3"><organizations default="ORG"><organization identifier="ORG"><title>${title}</title><item identifier="ITEM" identifierref="RES"><title>${title}</title></item></organization></organizations><resources><resource identifier="RES" type="webcontent" adlcp:scormType="sco" href="index.html"><file href="index.html"/></resource></resources></manifest>`;z.file('imsmanifest.xml',manifest);z.file('index.html',learner(d,ver));z.file('project.json',JSON.stringify(d,null,2));download(await z.generateAsync({type:'blob'}),`UCAN-${projectId}-SCORM-${ver==='12'?'1.2':'2004'}.zip`);$('publishStatus').className='success';$('publishStatus').textContent='Paquete creado correctamente.'}
async function webPackage(){const z=new JSZip(),d=state();z.file('index.html',learner(d));z.file('project.json',JSON.stringify(d,null,2));download(await z.generateAsync({type:'blob'}),`UCAN-${projectId}-Web.zip`)}
$('projectName').textContent=projectTitle;$('projectMeta').textContent=`${course||'Curso no especificado'} · ${level}`;
$('resourceFile').addEventListener('change',e=>{const f=e.target.files[0];if(!f)return;$('resourceUrl').value=f.name;$('resourceType').value=f.type.startsWith('image/')?'Imagen':$('resourceType').value;if(f.type.startsWith('image/')){const reader=new FileReader();reader.onload=()=>{imageData=String(reader.result);showResource();localDesign();improveWithAI()};reader.readAsDataURL(f)}else{$('resourcePreview').innerHTML=`<p><b>${esc(f.name)}</b> · ${Math.round(f.size/1024)} KB</p>`;localDesign()}});
let timer;$('resourceDescription').addEventListener('input',()=>{clearTimeout(timer);timer=setTimeout(()=>{if($('resourceDescription').value.trim().length>=8)localDesign()},650)});$('resourceUrl').addEventListener('input',()=>{clearTimeout(timer);timer=setTimeout(()=>{if($('resourceUrl').value.trim()){if(/\.(png|jpe?g|webp|gif)(\?|$)/i.test($('resourceUrl').value))imageData=$('resourceUrl').value;showResource();localDesign();if(imageData)improveWithAI()}},650)});
$('designBtn').onclick=()=>{localDesign();if(imageData)improveWithAI()};$('clearBtn').onclick=()=>{['activityTitle','objectives','instructions','question','expected','quiz1','quiz2','quiz3','resourceAlt'].forEach(id=>setValue(id,''));$('rubric').innerHTML='';rubricTotal();refreshPreview();scheduleSave()};$('showModelBtn').onclick=showModel;$('clearModelBtn').onclick=()=>{setValue('modelUrl','');$('modelPreview').innerHTML='<span class="muted">El modelo aparecerá aquí.</span>';$('modelStatus').textContent='Modelo eliminado.';refreshPreview();scheduleSave()};$('addCriterion').onclick=()=>{addRubricRow();changed()};$('previewBtn').onclick=refreshPreview;$('saveBtn').onclick=saveCloud;$('scorm12').onclick=()=>packageScorm('12');$('scorm2004').onclick=()=>packageScorm('2004');$('webZip').onclick=webPackage;document.querySelectorAll('input,textarea,select').forEach(el=>{if(!['resourceDescription','resourceUrl','resourceFile'].includes(el.id))el.addEventListener('input',changed)});
const local=localStorage.getItem(`ucan_v8_${projectId}`);if(local)try{apply(JSON.parse(local))}catch{}
renderModelSources();loadProjectInfo();loadCloud();
})();