(() => {
  const $ = id => document.getElementById(id);
  const isLocal = ['localhost','127.0.0.1'].includes(location.hostname);
  const API = isLocal ? '/api' : 'https://ucan-reality-lab.onrender.com/api';
  let token = localStorage.getItem('ucan_access_token') || '';
  let currentUser = null;
  let projectCache = [];
  const headers = (extra = {}) => ({ ...extra, Authorization: `Bearer ${token}` });
  const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const wait = ms => new Promise(resolve => setTimeout(resolve, ms));
  function showPanel(name) { ['loginPanel','registerPanel','forgotPanel'].forEach(id => $(id).classList.toggle('hidden', id !== name)); }
  function showLogin(message = '', clearSession = false) {
    if (clearSession) { token=''; currentUser=null; localStorage.removeItem('ucan_access_token'); }
    $('authView').classList.remove('hidden'); $('dashboardView').classList.add('hidden'); $('sessionArea').classList.add('hidden'); showPanel('loginPanel'); $('loginMessage').textContent=message;
  }
  function ensureProjectSearch(){if($('projectSearch'))return;const input=document.createElement('input');input.id='projectSearch';input.type='search';input.placeholder='Buscar por proyecto, curso, nivel o creador';input.setAttribute('aria-label','Buscar proyectos');input.addEventListener('input',renderProjects);$('projects').before(input)}
  function ensureAdminLink(user){let a=$('adminUsersLink');if(user.role==='admin'&&!a){a=document.createElement('a');a.id='adminUsersLink';a.className='btn secondary';a.href='/admin-users.html';a.textContent='Administrar cuentas';const session=$('sessionArea');const logout=$('logoutButton');session.insertBefore(a,logout||null)}if(a)a.classList.toggle('hidden',user.role!=='admin')}
  function showDashboard(user) { currentUser=user; $('authView').classList.add('hidden'); $('dashboardView').classList.remove('hidden'); $('sessionArea').classList.remove('hidden'); $('userBadge').textContent=`${user.full_name} · ${user.role}`; $('projectForm').classList.toggle('hidden',user.role==='reviewer'); const heading=$('projectsHeading'); if(heading)heading.textContent=user.role==='admin'?'Todos los proyectos':'Mis proyectos'; ensureAdminLink(user); ensureProjectSearch(); }
  async function parse(response){const body=await response.json().catch(()=>({}));if(!response.ok){const error=new Error(body.detail||`Error ${response.status}`);error.status=response.status;throw error}return body}
  async function fetchWithRetry(url, options={}, attempts=3){let last;for(let i=0;i<attempts;i++){try{return await fetch(url,options)}catch(e){last=e;if(i<attempts-1)await wait(1800*(i+1))}}throw last||new Error('No fue posible conectar con el servidor.')}
  async function wakeBackend(messageEl){try{if(messageEl)messageEl.textContent='Conectando con el servidor…';const r=await fetchWithRetry(`${API}/auth/login-readiness`,{},3);if(r.ok)return true}catch{}return false}
  async function deleteProject(projectId, projectTitle, button){const confirmed=window.confirm(`¿Desea borrar permanentemente el proyecto “${projectTitle}”?\n\nTambién se eliminarán la actividad, la rúbrica y la configuración guardada. Esta acción no se puede deshacer.`);if(!confirmed)return;button.disabled=true;button.textContent='Borrando…';try{const response=await fetchWithRetry(`${API}/projects/${encodeURIComponent(projectId)}`,{method:'DELETE',headers:headers()},2);if(response.status!==204)await parse(response);localStorage.removeItem(`ucan_v8_${projectId}`);localStorage.removeItem(`ucan_authoring_${projectId}`);await loadProjects()}catch(error){button.disabled=false;button.textContent='Borrar proyecto';window.alert(`No fue posible borrar el proyecto: ${error.message}`)}}
  function renderProjects(){const q=($('projectSearch')?.value||'').trim().toLowerCase();const ps=projectCache.filter(p=>[p.title,p.description,p.course,p.academic_level,p.owner_name,p.owner_email].join(' ').toLowerCase().includes(q));if(!ps.length){$('projects').innerHTML=`<p class="muted">${q?'No se encontraron proyectos.':'Todavía no hay proyectos.'}</p>`;return}$('projects').innerHTML=ps.map(p=>{const ownerName=p.owner_name||currentUser?.full_name||'Usuario';const ownerEmail=p.owner_email||currentUser?.email||'';const ownerLine=`<p class="project-owner"><strong>Creado por:</strong> ${esc(ownerName)}${ownerEmail?` · ${esc(ownerEmail)}`:''}</p>`;return `<article class="project" data-project-id="${esc(p.id)}"><h3>${esc(p.title)}</h3>${ownerLine}<p>${esc(p.description||'Sin descripción')}</p><p class="muted">${esc(p.course||'Curso no especificado')} · ${esc(p.academic_level)} · versión ${p.version}</p><div><a class="btn" href="/authoring-v8.html?project=${encodeURIComponent(p.id)}&title=${encodeURIComponent(p.title)}&course=${encodeURIComponent(p.course||'')}&level=${encodeURIComponent(p.academic_level||'')}">Abrir Studio v10.3</a><button type="button" class="secondary delete-project" data-project-id="${esc(p.id)}" data-project-title="${esc(p.title)}">Borrar proyecto</button></div></article>`}).join('');document.querySelectorAll('.delete-project').forEach(button=>button.addEventListener('click',()=>deleteProject(button.dataset.projectId,button.dataset.projectTitle,button)))}
  async function loadProjects(){$('projects').textContent='Cargando proyectos…';try{const endpoint=currentUser?.role==='admin'?`${API}/admin/projects`:`${API}/projects`;projectCache=await parse(await fetchWithRetry(endpoint,{headers:headers()},2));renderProjects()}catch(e){if(e.status===401){showLogin('La sesión expiró. Inicie sesión nuevamente.',true)}else{$('projects').innerHTML=`<p class="error">No se pudieron cargar los proyectos: ${esc(e.message||'servidor no disponible')}</p><button id="retryProjects" class="secondary">Intentar nuevamente</button>`;$('retryProjects')?.addEventListener('click',loadProjects)}}}
  async function verify(){if(!token)return showLogin();$('loginMessage').textContent='Recuperando su sesión…';try{const response=await fetchWithRetry(`${API}/auth/me`,{headers:headers()},2);const user=await parse(response);showDashboard(user);loadProjects()}catch(e){if(e.status===401||e.status===403){showLogin('La sesión expiró. Inicie sesión nuevamente.',true)}else{showLogin('No fue posible conectar con el servidor. Su sesión se conserva; presione Entrar o recargue la página para intentar nuevamente.',false)}}}
  $('loginTab').onclick=()=>showPanel('loginPanel'); $('registerTab').onclick=()=>showPanel('registerPanel'); $('forgotButton').onclick=()=>{$('forgotEmail').value=$('email').value;showPanel('forgotPanel')}; $('backLogin').onclick=()=>showPanel('loginPanel'); $('logoutButton').onclick=()=>showLogin('Sesión cerrada.',true); $('refreshButton').onclick=loadProjects;
  $('loginForm').onsubmit=async e=>{e.preventDefault();const m=$('loginMessage');const submit=e.submitter||e.target.querySelector('button[type="submit"],button');if(submit)submit.disabled=true;m.className='';m.textContent='Preparando el servidor…';try{await wakeBackend(m);m.textContent='Validando sus credenciales…';const response=await fetchWithRetry(`${API}/auth/login`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:$('email').value.trim(),password:$('password').value})},2);const b=await parse(response);token=b.access_token;localStorage.setItem('ucan_access_token',token);m.className='success';m.textContent='Acceso correcto.';showDashboard(b.user);loadProjects()}catch(err){m.className='error';if(err?.status===401)m.textContent=err.message;else if(err?.status===422)m.textContent=err.message;else m.textContent='No se pudo conectar con el backend de UCAN Reality Lab. Espere unos segundos y vuelva a presionar Entrar.'}finally{if(submit)submit.disabled=false}};
  $('registerForm').onsubmit=async e=>{e.preventDefault();const m=$('registerMessage');m.className='';m.textContent='Creando cuenta…';if($('registerPassword').value!==$('registerPasswordConfirm').value){m.className='error';m.textContent='Las contraseñas no coinciden.';return}try{await wakeBackend(m);const b=await parse(await fetchWithRetry(`${API}/auth/register`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({full_name:$('registerName').value,email:$('registerEmail').value.trim(),password:$('registerPassword').value})},2));token=b.access_token;localStorage.setItem('ucan_access_token',token);showDashboard(b.user);loadProjects()}catch(err){m.className='error';m.textContent=err.message||'No se pudo crear la cuenta.';if(/ya existe/i.test(err.message||''))$('forgotEmail').value=$('registerEmail').value.trim()}};
  $('forgotForm').onsubmit=async e=>{e.preventDefault();const m=$('forgotMessage');m.textContent='Procesando…';try{await wakeBackend(m);const b=await parse(await fetchWithRetry(`${API}/auth/forgot-password`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:$('forgotEmail').value.trim()})},2));m.className='success';m.textContent=b.message+(b.email_delivery_configured?'':' El correo saliente todavía no está configurado.')}catch(err){m.className='error';m.textContent=err.message||'No se pudo procesar la solicitud.'}};
  $('projectForm').onsubmit=async e=>{e.preventDefault();const m=$('formMessage');m.textContent='Creando…';try{const p=await parse(await fetchWithRetry(`${API}/projects`,{method:'POST',headers:headers({'Content-Type':'application/json'}),body:JSON.stringify({title:$('title').value,course:$('course').value,academic_level:$('level').value,description:$('description').value})},2));e.target.reset();location.href=`/authoring-v8.html?project=${encodeURIComponent(p.id)}&title=${encodeURIComponent(p.title)}&course=${encodeURIComponent(p.course||'')}&level=${encodeURIComponent(p.academic_level||'')}`}catch(err){m.className='error';m.textContent=err.message||'No se pudo crear el proyecto.'}};
  fetchWithRetry(`${API}/auth/registration-config`,{},2).then(parse).then(c=>$('domainHelp').textContent=`Dominios permitidos: ${c.allowed_domains.map(d=>'@'+d).join(', ')}`).catch(()=>{});verify();
})();