(()=>{
'use strict';
const VERSION='11.2 Standalone';
const $=(s,r=document)=>r.querySelector(s);
function applyTheme(theme){document.documentElement.dataset.theme=theme;localStorage.setItem('ucan_theme',theme);const b=$('#ucanThemeToggle');if(b){b.textContent=theme==='dark'?'☀️ Modo claro':'🌙 Modo oscuro';b.setAttribute('aria-pressed',String(theme==='dark'));}}
function installStyles(){if($('#ucanInstitutionalStyles'))return;const s=document.createElement('style');s.id='ucanInstitutionalStyles';s.textContent=`
:root{--ucan-green:#08775d;--ucan-dark:#073f32;--ucan-gold:#fed141;--ucan-bg:#eef5f2;--ucan-card:#fff;--ucan-text:#14231e;--ucan-muted:#52675f;--ucan-border:#d5e4dd;color-scheme:light}
:root[data-theme="dark"]{--ucan-bg:#101916;--ucan-card:#18231f;--ucan-text:#eef8f4;--ucan-muted:#b8cbc3;--ucan-border:#365148;color-scheme:dark}
html,body{background:var(--ucan-bg)!important;color:var(--ucan-text)!important}body{min-height:100vh;display:flex;flex-direction:column}main{flex:1}.card,.step,.model-card,.publish-box,.box,.project{background:var(--ucan-card)!important;color:var(--ucan-text)!important;border-color:var(--ucan-border)!important}.muted{color:var(--ucan-muted)!important}
.ucan-skip{position:fixed;left:10px;top:-80px;z-index:99999;background:#fff;color:#073f32;padding:.65rem 1rem;border-radius:8px;font-weight:800}.ucan-skip:focus{top:10px}
header.ucan-shell-header{background:linear-gradient(120deg,var(--ucan-dark),var(--ucan-green))!important;color:#fff!important;padding:.8rem 1.2rem!important;position:relative;z-index:20;min-height:104px}
.ucan-shell-row{max-width:1480px;margin:auto;display:grid;grid-template-columns:minmax(245px,1fr) minmax(290px,1.25fr) minmax(245px,1fr);gap:1rem;align-items:center}.ucan-shell-brand{display:flex;align-items:center;gap:12px}.ucan-shell-brand img{display:block;object-fit:contain}.ucan-shell-inter{width:min(235px,28vw);max-height:72px}.ucan-shell-ucan{width:76px;height:76px}.ucan-shell-title{text-align:center}.ucan-shell-title h1{margin:0;font-size:clamp(1.4rem,2.2vw,2rem);color:#fff}.ucan-shell-title p{margin:.25rem 0 0;color:#fff}.ucan-shell-actions{display:flex;justify-content:flex-end;align-items:center;gap:.45rem;flex-wrap:wrap}.ucan-shell-actions button{margin:0;padding:.58rem .75rem;background:#e4f0eb;color:#075e49;border:0;border-radius:9px;font-weight:800;cursor:pointer}
.ucan-shell-footer{margin-top:2rem;background:#073f32;color:#fff;padding:1rem 1.25rem}.ucan-shell-footer-inner{max-width:1240px;margin:auto;display:flex;justify-content:space-between;gap:1rem;flex-wrap:wrap;align-items:center}.ucan-shell-footer a{color:#fed141}.ucan-shell-footer p{margin:.15rem 0}.ucan-version{font-weight:800;color:#fed141}
@media(max-width:900px){.ucan-shell-row{grid-template-columns:1fr}.ucan-shell-brand,.ucan-shell-actions{justify-content:center}.ucan-shell-title{order:2}.ucan-shell-actions{order:3}.ucan-shell-brand{order:1}.ucan-shell-inter{width:min(220px,66vw);max-height:62px}.ucan-shell-ucan{width:62px;height:62px}header.ucan-shell-header{position:relative!important;top:auto!important}}
`;document.head.appendChild(s)}
function logoFallback(img,label){img.addEventListener('error',()=>{img.replaceWith(Object.assign(document.createElement('strong'),{textContent:label}))},{once:true})}
function collectActions(old){const candidates=[...old.querySelectorAll('a,button')];return candidates.filter(node=>!candidates.some(other=>other!==node&&other.contains(node)))}
function buildHeader(){const old=$('body > header');if(!old||old.classList.contains('ucan-shell-header'))return;const titleNode=$('h1',old);const oldTitle=titleNode?.textContent?.trim()||'UCAN Reality Lab';const titleWrap=titleNode?.parentElement;const subtitleNode=titleWrap?[...titleWrap.children].find(n=>n!==titleNode&&['DIV','P','SPAN','SMALL'].includes(n.tagName)):null;const oldSubtitle=subtitleNode?.textContent?.trim()||'';const preserved=collectActions(old);const h=document.createElement('header');h.className='ucan-shell-header';h.innerHTML=`<div class="ucan-shell-row"><div class="ucan-shell-brand" aria-label="Identidad institucional"><img class="ucan-shell-inter" alt="Universidad Interamericana de Puerto Rico, Recinto de San Germán"><img class="ucan-shell-ucan" alt="UCAN PPOHA"></div><div class="ucan-shell-title"><h1>${oldTitle}</h1>${oldSubtitle?`<p>${oldSubtitle}</p>`:''}</div><div class="ucan-shell-actions"></div></div>`;const inter=$('.ucan-shell-inter',h),ucan=$('.ucan-shell-ucan',h);inter.src=window.UCAN_INTER_LOGO||'/assets/inter-san-german.webp';ucan.src=window.UCAN_UCAN_LOGO||'/assets/ucan-ppoha.webp';logoFallback(inter,'Inter San Germán');logoFallback(ucan,'UCAN');const actions=$('.ucan-shell-actions',h);preserved.forEach(n=>actions.appendChild(n));const theme=document.createElement('button');theme.id='ucanThemeToggle';theme.type='button';theme.addEventListener('click',()=>applyTheme(document.documentElement.dataset.theme==='dark'?'light':'dark'));actions.appendChild(theme);old.replaceWith(h)}
function buildFooter(){if($('.ucan-shell-footer'))return;const f=document.createElement('footer');f.className='ucan-shell-footer';f.innerHTML=`<div class="ucan-shell-footer-inner"><div><p><strong>Universidad Interamericana de Puerto Rico</strong></p><p>Recinto de San Germán · UCAN PPOHA</p></div><div><p class="ucan-version">UCAN Reality Lab ${VERSION}</p><p>Correo: <a href="mailto:UCAN_PPOHA@intersg.edu">UCAN_PPOHA@intersg.edu</a></p></div></div>`;document.body.appendChild(f)}
function init(){installStyles();if(!$('.ucan-skip')){const skip=document.createElement('a');skip.className='ucan-skip';skip.href='#main-content';skip.textContent='Saltar al contenido principal';document.body.prepend(skip)}const main=$('main');if(main&&!main.id)main.id='main-content';buildHeader();buildFooter();applyTheme(localStorage.getItem('ucan_theme')||'light')}
document.readyState==='loading'?document.addEventListener('DOMContentLoaded',init):init();
})();